version: "3.8"

services:
  nginx:
    image: docker.io/library/nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ../portfolio/aspnet-api/images:/usr/share/nginx/html/images:ro
    restart: always
    networks:
      shared:
        aliases:
          - web-proxy

volumes:
  pg_data:

networks:
  shared:
    external: true
    name: shared_net
